import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import MysticSymbolsEffect from './Layout-component/BubbleEffect/MysticSymbolsEffect';
import StoreInitializer from './Layout-component/StoreInitializer';
import { getUser } from '@/lib/supabse/server';
import { ChevronLeft, Circle, Menu } from 'lucide-react';
import CircleButtonWithAlert from './components/shared/CircleButtonWithAlert';
import { headers } from 'next/headers';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getUser();

  // 현재 경로 가져오기
  const headersList = headers();
  const pathname = headersList.get('x-pathname') || '';

  // 숨길 경로 목록
  const hiddenNavPaths = ['/start', '/question', '/health-info'];
  const shouldShowNav = !hiddenNavPaths.includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative mx-auto max-w-lg`}
      >
        {shouldShowNav && (
          <div className="w-full h-12 absolute top-0 z-50 flex px-6 items-center justify-between">
            <ChevronLeft color="#9CA3AF" size={32} />
            <Menu color="#9CA3AF" size={32} />
          </div>
        )}

        {children}

        <StoreInitializer currentUser={currentUser} />
        <MysticSymbolsEffect />

        {shouldShowNav && (
          <div className="fixed bottom-6 right-6 z-50 ml-auto w-fit flex items-center justify-center">
            <CircleButtonWithAlert />
          </div>
        )}
      </body>
    </html>
  );
}
